export const getDatePickerStyles = () => ({
	root: "flex flex-col gap-1",
	label: "text-sm font-medium text-[var(--color-text)]",
	group: [
		"flex items-center border border-[var(--color-border)] rounded px-2 py-1 gap-1",
		"bg-[var(--color-surface)]",
		"data-[focused]:border-[var(--color-primary)]",
		"data-[disabled]:opacity-50 data-[disabled]:cursor-not-allowed",
		"data-[invalid]:border-[var(--color-danger)]",
	].join(" "),
	input: "flex items-center flex-1 gap-0",
	segment: [
		"rounded px-0.5 text-sm text-[var(--color-text)] outline-none",
		"data-[placeholder]:text-[var(--color-textMuted)]",
		"data-[focused]:bg-[var(--color-primary)] data-[focused]:text-white",
		"data-[type=literal]:text-[var(--color-textMuted)]",
	].join(" "),
	button: [
		"p-1 rounded text-[var(--color-textMuted)] outline-none",
		"hover:text-[var(--color-text)]",
		"focus-visible:outline-2 focus-visible:outline-[var(--color-primary)]",
	].join(" "),
	description: "text-sm text-[var(--color-textMuted)]",
	error: "text-sm text-[var(--color-danger)]",
	popover: "z-50 shadow-lg rounded bg-[var(--color-surface)] border border-[var(--color-border)] p-3",
	calendar: "flex flex-col gap-2",
	calendarHeader: "flex items-center justify-between mb-1",
	calendarHeading: "text-sm font-medium text-[var(--color-text)]",
	navButton: [
		"p-1 rounded text-[var(--color-textMuted)] outline-none text-xs",
		"hover:text-[var(--color-text)]",
		"focus-visible:outline-2 focus-visible:outline-[var(--color-primary)]",
	].join(" "),
	grid: "border-collapse w-full",
	cell: [
		"w-8 h-8 text-xs text-center rounded-full cursor-default outline-none flex items-center justify-center",
		"hover:bg-[var(--color-surface)]",
		"data-[today]:font-bold data-[today]:text-[var(--color-primary)]",
		"data-[selected]:bg-[var(--color-primary)] data-[selected]:text-white",
		"data-[selection-start]:rounded-full data-[selection-end]:rounded-full",
		"data-[outside-month]:opacity-30",
		"data-[disabled]:opacity-30",
		"data-[unavailable]:line-through data-[unavailable]:text-[var(--color-danger)]",
		"focus-visible:outline-2 focus-visible:outline-[var(--color-primary)]",
	].join(" "),
	rangeSeparator: "text-[var(--color-textMuted)] px-1 text-sm",
})
