export type { ActionCtx } from "./action-context"
export { ActionContext } from "./action-context"
export type { BreadcrumbItem, BreadcrumbNode } from "./components/breadcrumb"
export { Breadcrumb, BreadcrumbSchema } from "./components/breadcrumb"
export type { ButtonNode } from "./components/button"
export { Button, ButtonSchema } from "./components/button"
export type { CardNode } from "./components/card"
export { Card, CardSchema } from "./components/card"
export type { CheckboxGroupNode, CheckboxNode } from "./components/checkbox"
export { Checkbox, CheckboxGroup, CheckboxGroupSchema, CheckboxSchema } from "./components/checkbox"
export type { DatePickerNode, DateRangePickerNode } from "./components/date-picker"
export { DatePicker, DatePickerSchema, DateRangePicker, DateRangePickerSchema } from "./components/date-picker"
export type { DialogNode } from "./components/dialog"
export { Dialog, DialogSchema } from "./components/dialog"
export type { FormNode } from "./components/form"
export { Form, FormSchema } from "./components/form"
export type { FlexNode, GridNode } from "./components/layout"
export { Flex, FlexSchema, Grid, GridSchema } from "./components/layout"
export type { MenuItemEntry, MenuNode } from "./components/menu"
export { Menu, MenuSchema } from "./components/menu"
export type { NumberFieldNode } from "./components/number-field"
export { NumberField, NumberFieldSchema } from "./components/number-field"
export type { PopoverNode } from "./components/popover"
export { Popover, PopoverSchema } from "./components/popover"
export type { RadioGroupNode, RadioNode } from "./components/radio"
export { Radio, RadioGroup, RadioGroupSchema, RadioSchema } from "./components/radio"
export type { SelectItem, SelectNode } from "./components/select"
export { Select, SelectSchema } from "./components/select"
export type { SwitchNode } from "./components/switch"
export { Switch, SwitchSchema } from "./components/switch"
export type { TableColumn, TableNode, TableRow } from "./components/table"
export { Table, TableSchema } from "./components/table"
export type { TabItem, TabsNode } from "./components/tabs"
export { Tabs, TabsSchema } from "./components/tabs"
export type { TextNode } from "./components/text"
export { Text, TextSchema } from "./components/text"
export type { TextFieldNode } from "./components/text-field"
export { TextField, TextFieldSchema } from "./components/text-field"
export type { TooltipNode } from "./components/tooltip"
export { Tooltip, TooltipSchema } from "./components/tooltip"
export type { FormStateCtx } from "./form-state"
export { FormStateContext } from "./form-state"
// ↑ Component schemas are exported for consumers to validate a2UI JSON before
// passing it to A2Renderer. They are not used internally — see schema/node.ts.
export { defaultRegistry, registerAllComponents } from "./registry/defaultRegistry"
export type { A2Registry } from "./registry/registry"
export { createRegistry, getRegistry, registerComponent } from "./registry/registry"
export type { NodeValidatorResult } from "./registry-schema"
export { buildRegistrySchema, toJsonSchema } from "./registry-schema"
export { A2ErrorBoundary } from "./renderer/A2ErrorBoundary"
export { A2Renderer } from "./renderer/A2Renderer"
export type { A2NodeInput } from "./schema"
export { A2NodeSchema, parseNode, safeParseNode } from "./schema"
export type {
	A2ComponentType,
	A2Node,
	A2RendererProps,
	ComponentEntry,
	ComponentRegistry,
	SchemaLike,
} from "./types"
export { extractA2ui, stripStreamingA2ui } from "./utils/extractA2ui"

export const VERSION = "0.1.0-preview.0"
